name: coverage

on: [push, pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      run: |
        install.packages("covr")
        install.packages("remotes")
        remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}
    - name: Run test coverage
      run: covr::codecov()
      shell: Rscript {0}
