name: R-CMD-check-coverage

on:
  push:
  pull_request:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    container: rocker/r-ver:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages("remotes")'
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        Rscript -e 'install.packages("covr")'

    - name: Test coverage
      run: |
        Rscript -e 'covr::codecov()'

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
